"on":
    push:
        branches:
            - main
name: Deploy to irmai-tool-1
jobs:
    porter-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set Github tag
              id: vars
              run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
            - name: Setup porter
              uses: porter-dev/setup-porter@v0.1.0
            - name: Porter Login
              run: |
                porter config set-host https://dashboard.porter.run
                porter auth login --token ${{ secrets.PORTER_TOKEN }} --project 14185 --cluster 4465
            - name: Deploy stack
              timeout-minutes: 30
              run: exec porter apply
              env:
                  PORTER_CLUSTER: 4465
                  PORTER_HOST: https://dashboard.porter.run
                  PORTER_PROJECT: 14185
                  PORTER_APP_NAME: irmai-tool-1
                  PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
                  PORTER_TOKEN: ${{ secrets.PORTER_APP_14185_4465 }}
                  PORTER_PR_NUMBER: ${{ github.event.number }}
                  PORTER_REPO_NAME: ${{ github.event.repository.name }}