on:
  push:
    branches:
    - aniket_gap_analysis_codebase
name: Deploy to Porter - Aniket branch
jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set Github tag
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Setup porter
      uses: porter-dev/setup-porter@v0.1.0
    - name: Deploy stack
      timeout-minutes: 30
      run: exec porter apply 
      env:
        PORTER_CLUSTER: 4465
        PORTER_HOST: https://dashboard.porter.run
        PORTER_PROJECT: 14185
        PORTER_APP_NAME: irmai-tool-2
        PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
        PORTER_TOKEN: ${{ secrets.PORTER_APP_14185_4465 }}
        PORTER_DEPLOYMENT_TARGET_ID: 1eedb028-e013-4c3a-a842-baa580648df7
